### ISSUE TITLE
Add new courses starting Fall 2020

### ISSUE THREAD

**Issue by limjiayi** [OMSCentral/omscentral#10]
CS 6457 Video Game Design
CS 7643 Deep Learning
INTA 6450 Data Analytics and Security (OMSCy)
INTA 6742 Modelling, Simulation, and Military Gaming (OMSCy)

CSE 6748 Applied Analytics Practicum (OMSA) Also noticed the OMSA practicum is missing from the list. Not sure if we want to add this since it isn't a taught course.

PUBP 6502 Information and Communications Technology Policy is also missing for OMSCy, though I'm not sure when it started being offered.

**Comment by mehmetbajin** [comment]
Courses that are available online in Fall 2020 have been added. Remaining courses will be added once offered.

**Comment by limjiayi** [comment]
All of the courses I listed are already being offered.

**Comment by mehmetbajin** [comment]
- CS 6457 has a cap of 0 (no students registered)
- CS 7643 has a cap of 0 (no students registered)
- INTA 6450 appears in omscentral.com
- INTA 6742 appears in omscentral.com
- PUBP 6502 appears in omscentral.com

@limjiayi Based on this, what changes are still needed?

**Comment by limjiayi** [comment]
I opened OMSCentral in an incognito tab but don't see these courses listed on https://omscentral.com/courses?

Students have started registering for CS 6457 Video Game Design and CS 7643 Deep Learning, too.
