### ISSUE TITLE
Is there a way to add a class not listed?

### ISSUE THREAD

**Issue by Clean-Pigeon** [OMSCentral/omscentral#117]
I noticed the following courses not listed. Is there a way to list classes ourselves? Thank you for your work.

INTA 6103 - International Security
ECE 8853 - Introduction to Cyber-Physical Electric Energy Systems
ECE 8813 - Introduction to Cyber-Physical Systems Security
ECE 6150 - Computational Aspects of Cyber-Physical Systems
ECE 8823 - Cyber Physical Design and Analysis
ECE 8863 - Principles of Smart Electricity Grids
ECE 8873 - Advanced Hardware Oriented Security and Trust

reference:
https://pe.gatech.edu/sites/default/files/degrees/cybersecurity/oms-cybersecurity-course-list.pdf

**Comment by mehmetbajin** [comment]
Please open a pull request updating the following file:

https://github.com/OMSCentral/omscentral/blob/staging/server/database/data/courses.ts

Thank you!!

**Comment by Clean-Pigeon** [comment]
Added pull request. I hope this helps. 
https://github.com/OMSCentral/omscentral/pull/125

**Comment by mehmetbajin** [comment]
> Added pull request. I hope this helps.
> #125

Merged. Thank you!
