### ISSUE TITLE
Course statistics should dynamically update based on active filters

### ISSUE THREAD

**Issue by datu925** [OMSCentral/omscentral#123]
The stats for a given course are for all reviews available on the site. This limits user's ability to understand trends and focus on more recent and relevant data. omscentral has a significant number of reviews from 2015-2018, so for some classes these out-of-date reviews dominate more recent ones.

As an interesting case study, CS6035 received high ratings initially (yearly average ranges from 3.75-3.98 for 2015 to 2018), but appears to get much worse afterward (3.04 average for 2019-2020). This story is lost because users can't disaggregate the data.

The most immediate way to address this is probably to make the displayed metrics always be representative of the reviews currently matching the filters on that page. That way users can filter to more recent reviews if they're interested. I also think a similar filter should be added to the main courses page, though my impression is that may be a larger lift.

**Comment by mehmetbajin** [comment]
Thank you for the feedback, @datu925. I support you here.

Currently, the metrics are calculated server-side any time a review object is mutated. This allows the calculations to take place just once for all clients.

Pre-computation seems infeasible for the new use case of reflecting the metrics just for the reviews matching the current filters. There are simply too many combinations of filters.

Instead, I recommend updating `graphql/Query/reviews.graphql` and `server/src/api/query/reviews.ts` to return the aggregate metrics for the current search configuration:

```
![image](https://user-images.githubusercontent.com/10424048/116394699-40bcbd00-a7f1-11eb-840a-4020aebeabe5.png)
```

**Comment by mehmetbajin** [comment]
I think another, better solution is to introduce a product experience in a new view for slicing/dicing the data.

I'm imagining a dynamic chart that updates its display as input parameters such as course(s), semester(s), etc. are updated to surface information such as trends, statistical aggregations and more.

**Comment by datu925** [comment]
I definitely like the idea of a new view for trends/analysis. That would give a lot of new functionality to the user.

That feels like a more substantial effort (which I am happy to contribute to). In the meantime, do you have any objections to me trying your suggested approach and sending a PR that provides some of this functionality in the short-term?

**Comment by mehmetbajin** [comment]
> I definitely like the idea of a new view for trends/analysis. That would give a lot of new functionality to the user.
> 
> That feels like a more substantial effort (which I am happy to contribute to). In the meantime, do you have any objections to me trying your suggested approach and sending a PR that provides some of this functionality in the short-term?

Go for it! PRs are always welcome. Please take a moment to familiarize yourself with the existing coding patterns to avoid introducing new patterns.

**Comment by mehmetbajin** [comment]
Short-term solution has been implemented.
