### ISSUE TITLE
Update README to include a system architecture overview

### ISSUE THREAD

**Issue by SohamGhormade** [OMSCentral/omscentral#138]
The README.md files in client, server and the top level folder in the repo provide links to the tools used which is good.
However, as a potential contributor, it would be better for me to understand the workflow with the tools.

Basically, what is the sequence of events? how does the system architecture diagram look like?

Given these questions, will attempt to summarize my understanding below.
However, in case, I am missing a detail, please share.
Thanks

### Server 
- Languages: Typescript 
- Database : Postgres

###  Client
- Languages: Typescript (.tsx)
- Framework: React 

### Server and Client 
- GraphQL for reading and writing to postgres database
-  Client likely indirectly writes to the server 

### Package management 
- via npm 

### User Authentication 
- Via Firebase as mentioned [here](https://github.com/OMSCentral/omscentral/tree/staging/server#firebase)
  
### Add a review
- Client  authenticates user via Firebase
- User writes review.
- Server writes to postgres database using GraphQL

## Action item
- If someone can confirm the understanding above looks right, it would be great. Alternatively, any suggestions on where to look e.g if the current architecture keyed off an existing model used elsewhere, please share. Thanks !

**Comment by ghormadesoham** [comment]
As an update, #152 adds a section about system architecture and a system architecture diagram.
Given that update, this issue can be closed once #152 has been merged.
This is because #152 addresses this issue.

**Comment by ghormadesoham** [comment]
As an update #153  has been merged.
Given that update, this issue can be closed since that PR resolves this issue.
