### ISSUE TITLE
Simulation should be called ISYE 6644: Simulation and Modeling for Engineering and Science

### ISSUE THREAD

**Issue by nickcorona** [OMSCentral/omscentral#192]
ISYE 6644: Simulation and Modeling for Engineering and Science

See:https://omscs.gatech.edu/isye-6644-simulation-and-modeling-engineering-and-science

**Comment by mehmetbajin** [comment]
https://github.com/OMSCentral/omscentral/commit/95c286a6f51f79e16b5387d76278eaf38bf95d05
