### ISSUE TITLE
Is there a way to report reviews?

### ISSUE THREAD

**Issue by SchmidtSamuelo** [OMSCentral/omscentral#193]
Just curious, I don't see anything on the site that would indicate a way to report any content in reviews but have seen reviews that were abusive towards TAs or otherwise inappropriate get removed before so I was curious if there was a way to report them.

**Comment by mehmetbajin** [comment]
Added the following:

![image](https://user-images.githubusercontent.com/10424048/140249638-5c6d7cd3-92f3-41f8-a23a-6208e4725556.png)
