### ISSUE TITLE
cs 7470 mobile-ubiquitous-computing is missing

### ISSUE THREAD

**Issue by nickcorona** [OMSCentral/omscentral#194]
CS 7470 mobile ubiquitous computing is missing from OMSCS central.

[See here: https://omscs.gatech.edu/cs-7470-mobile-ubiquitous-computing](https://omscs.gatech.edu/current-courses)

**Comment by mehmetbajin** [comment]
https://github.com/OMSCentral/omscentral/commit/95c286a6f51f79e16b5387d76278eaf38bf95d05
