### ISSUE TITLE
Make dataset available for download/analysis

### ISSUE THREAD

**Issue by driscoll42** [OMSCentral/omscentral#195]
I'd like to do some compare/contrasting of the classes and also to CIOS just to see what things look like over time. Ideally there'd be a way to download the dataset to review with, preferably each review with the scores given, class, and semesters. I don't need the text of the review, though that could be interesting as well. This is basically the same as #16 , and I think ideally it'd just be a .csv to download.

**Comment by mehmetbajin** [comment]
@driscoll42 Awesome! Sounds like this would help a lot of folks. What do you think about integrating the analysis directly into omscentral.com in a user-friendly UI?

**Comment by driscoll42** [comment]
I wouldn't mind helping do that at all, though I admit I have zero typescript/javascript knowledge, all my analysis has been done in python. I did get all the CIOS data, and actually all the data from https://critique.gatech.edu/ for the OMS classes as well. My only concern with doing a OMSCentral vs CIOS compare and putting it on OMSCentral semi-officially would be if there are any issues in terms of ToS, etc... with using GT's data. I would hate to get OMSCentral in trouble.

That being said, assuming kinks worked out, sure. Not really sure what's possible but open to exploring it.

**Comment by mehmetbajin** [comment]
@driscoll42 Let's continue the conversation in Slack. I've sent you an invite.
