### ISSUE TITLE
CS-8803-O08: Compilers: Theory & Practice needs to be marked as foundational

### ISSUE THREAD

**Issue by ghlai9665** [OMSCentral/omscentral#205]
It's a foundational course but doesn't have the "f" mark right now.

**Comment by mehmetbajin** [comment]
@ghlai9665 Thanks for flagging this, nice catch!

The fix is a one-liner update here:

https://github.com/OMSCentral/omscentral/blob/staging/server/database/data/courses.ts#L486

Would you be able to open a PR for this?
