### ISSUE TITLE
[bug] Cannot create new reviews

### ISSUE THREAD

**Issue by fernandoprocy** [OMSCentral/omscentral#207]
Hi, one of the latest commits may have broken the create review functionality. Even logged in (Google/Github SSO), a message pops up saying that we must be logged in to submit reviews.

**Comment by winkie5970** [comment]
+1, also happening when logged in with Facebook SSO

**Comment by calebkm** [comment]
+1, same issue.

**Comment by bradleygrant** [comment]
Also experiencing this issue on Google Chrome and Microsoft Edge.

**Comment by bradleygrant** [comment]
Looks like the most recent reviews were all left on 1/3 -- none since then.

**Comment by fernandoprocy** [comment]
Looks like it's been fixed. I'll be closing this issue for now.
