### ISSUE TITLE
CS6603 AIES not listed for ML specialization

### ISSUE THREAD

**Issue by diegodaa** [OMSCentral/omscentral#209]
According to the website, AIES counts toward ML.  But if you filter for ML, the course gets filtered out

https://omscs.gatech.edu/specialization-machine-learning

**Comment by mehmetbajin** [comment]
@diegodaa Nice catch, thanks for flagging this!

To patch this issue, we just need to update the following file:

[`server/database/data/specializations.ts`](https://github.com/OMSCentral/omscentral/blob/staging/server/database/data/specializations.ts)

Would you be able to open a PR for this?

**Comment by savitoj98** [comment]
CS6603 AIES is also missing from Interactive intelligence specialization https://omscs.gatech.edu/specialization-interactive-intelligence

**Comment by savitoj98** [comment]
#226
