### ISSUE TITLE
CS 6675: Advanced Internet Systems & Applications missing

### ISSUE THREAD

**Issue by zhannur** [OMSCentral/omscentral#215]
https://omscs.gatech.edu/cs-6675-advanced-internet-systems-and-applications

**Comment by mehmetbajin** [comment]
@zhannur Thanks for flagging this!

To create this course, we just need to update the following file:

https://github.com/OMSCentral/omscentral/blob/ce350403a4d867f7fae54a4f4735357dbe05296d/server/database/data/courses.ts

Would you be able to open a PR for this?

**Comment by zhannur** [comment]
The course is there actually, there's just no reviews for the course. Closing the issue.
