### ISSUE TITLE
API to consume data

### ISSUE THREAD

**Issue by joshiparth1000** [OMSCentral/omscentral#236]
Is there an API I can use to consume the data?

**Comment by mehmetbajin** [comment]
> Is there an API I can use to consume the data?

Not at this time. Supporting this would require updating the terms and conditions and collecting consent from users (not to mention developing a secure API), and I just have not had the time to prioritize this over other more urgent needs.

**Comment by joshiparth1000** [comment]
Is there a way I can get the relationships between specialization and course? Like which course is part of which specialization . I am thinking of using that information help me select the courses for upcoming semester. Having raw data ready to consume would be much better than going through the official site or OMSCS central websites.

**Comment by mehmetbajin** [comment]
> Is there a way I can get the relationships between specialization and course? Like which course is part of which specialization . I am thinking of using that information help me select the courses for upcoming semester. Having raw data ready to consume would be much better than going through the official site or OMSCS central websites.

https://github.com/OMSCentral/omscentral/blob/staging/server/database/data/specializations.ts
