### ISSUE TITLE
New Courses: Network Science, Game AI, Distributed Computing and Systems Issues in Cloud Computing

### ISSUE THREAD

**Issue by limjiayi** [OMSCentral/omscentral#33]
CS 7280: Network Science, counts towards the Computing Systems specialization
CS 7632: Game AI, counts towards the Interactive Intelligence specialization
CS 7210: Distributed Computing, counts towards the Computing Systems specialization
CS 8803 O12: Systems Issues in Cloud Computing, counts towards the Computing Systems specialization

I also noticed that there are 2 listings for Data Analytics and Security:
- INTA-6450 Data Analytics & Security
- INTA-8803 Data Analytics & Security

Should just keep the INTA 6450 version as that's the official course number now.

**Comment by mehmetbajin** [comment]
@limjiayi Which ones, if any, are foundational?

**Comment by limjiayi** [comment]
@mehmetbajin All 4 classes are considered foundational since they count towards a specialization.

**Comment by mehmetbajin** [comment]
> @mehmetbajin All 4 classes are considered foundational since they count towards a specialization.

Have you noticed any other inconsistencies in omacentral.com? Thank you for your help!

**Comment by limjiayi** [comment]
> Have you noticed any other inconsistencies in omacentral.com? Thank you for your help!

No problem, I haven't noticed any other inconsistencies but I'll create issues here if I do.

**Comment by mehmetbajin** [comment]
Updated in 5cdf3f19796d72d2fa13208da19779050493f6e7.
